export { C } from "./colors";
export {
  getTerminalWidth,
  truncate,
  showLoading,
  clearLoading,
  clearScreen,
  setQuietProgress,
  flushStdout,
  progressBar,
  stripAnsi,
  renderMarkdown,
} from "./terminal";
export { type Credentials, loadCredentials, makeAuthHeader } from "./credentials";
export { jiraGet, jiraPost, jiraPut, jiraDelete, jiraUpload, resolveMediaId, jiraSearch, jiraSearchPaginated, jiraBulkFetch, jiraBulkChangelog, type BulkChangelogHistory, type PaginatedSearchResult } from "./api";
export {
  type IssueData,
  type SprintData,
  type CommentData,
  type IssueLinkData,
  type AttachmentData,
  getStr,
  getObj,
  getNested,
  parseIssue,
  parseIssues,
  parseSprint,
  parseComments,
  parseIssueLinks,
  extractTeam,
} from "./parser";
export { type AdfNode, markdownToAdf, adfToMarkdown, jiraWikiToMarkdown, decodeMediaPlaceholder, makeMediaPlaceholder } from "./markdown";
export {
  type CommandResult,
  runCommand,
  runCommandResult,
  getCacheDir,
  readFileArg,
  ticketFromBranch,
  ensureInsideGitRepo,
  getCurrentBranch,
  gitBranchExists,
  gitRemoteBranchExists,
  type GitWorktree,
  listGitWorktrees,
  findWorktreeByName,
  formatRelativeDate,
  abbreviateName,
  PriorityMap,
  PriorityNames,
  formatElapsed,
} from "./util";
export {
  type PRData,
  type PRMap,
  type PRAuthorActivity,
  type PRCheckRun,
  type PRReview,
  type PRMergeStatus,
  type PRDetail,
  type PRGateResult,
  fetchPRsForTickets,
  getPRForTicket,
  getPRForBranch,
  fetchPRDetail,
  fetchPRDetailForBranch,
  validateReviewGate,
  formatPRReviewLabel,
  formatPRChecksLabel,
  getRepoForProject,
  getAllMappedRepos,
  fetchRecentPRAuthorActivity,
  type MyPRSummary,
  fetchMyPRs,
  createPullRequest,
  openPullRequest,
} from "../github";
export {
  type FlowState,
  cacheIssues,
  diffAndCacheIssues,
  type SyncChange,
  type FieldChange,
  cacheSingleIssue,
  cacheUserMapping,
  getUserAccountId,
  searchCache,
  getCachedKeys,
  getCachedIssue,
  getFlowState,
  getFlowStateForBranch,
  getCachedIssuesRaw,
  findIssuesContaining,
  getTimelineDates,
  clearCache,
  rebuildFtsIndex,
  isValidKey,
  resolveKey,
  getLastSyncTime,
  setLastSyncTime,
  getCacheStats,
  upsertFlowState,
  type KeyResolveResult,
  getLocalMineIssues,
  getLocalSprintData,
  getWasMineKeys,
  getIdKeyMap,
  getBackfillKeys,
  getRecentCachedKeys,
  cacheChangelog,
  getChangelogEntries,
  resetChangelogSynced,
  getEmbeddingStats,
  invalidateEmbeddingCache,
  type CachedIssue,
  type CacheSearchOpts,
  type CacheStats,
  type UserRecord,
  getAllUsers,
  getUser,
  getMainUser,
  getUsersByRole,
  upsertUser,
  upsertUsersFromSync,
  updateUserFields,
  findUserByNameOrId,
  cachePages,
  getPageFromCache,
  searchPagesInCache,
  type CachedPage,
  type CachedPR,
  cachePRs,
  getCachedPRs,
  clearPRCache,
} from "./cache";
export { highlightTerms, findExcerpts } from "./fuzzy";
export { isStopWord, invalidateSearchIndex } from "./search";
export { searchCacheHybrid, type HybridSearchOpts } from "./hybrid-search";
export { isOllamaAvailable, isModelAvailable } from "./embeddings";
export { syncEmbeddings } from "./embed-sync";
export {
  type TimelineDate,
  type TimelineTicket,
  type TimelineEdge,
  type TimelineEvent,
  type TimelineData,
  fetchTimelineDates,
  extractTimelineDates,
  extractPreviousAssignees,
  syncTimelineDates,
  expandRelatedTickets,
  buildGraph,
  buildTimeline,
} from "./timeline";
export {
  type HistoryChange,
  type HistoryEvent,
  type HistoryData,
  fetchFullChangelog,
  parseHistory,
} from "./history";
export {
  type ExportInput,
  type ExportOptions,
  DEFAULT_BOT_AUTHORS,
  isBotAuthor,
  demoteHeadings,
  buildTicketMarkdown,
} from "./export";
export {
  resolveSpaceId,
  resolveSpaceKey,
  getConfluencePage,
  createConfluencePage,
  updateConfluencePage,
  getPagesInSpace,
  searchConfluence,
  type ConfluencePage,
} from "./confluence";
